### ISSUE TITLE
No way to pass no arguments?

### ISSUE THREAD

**Issue by ljharb** [js-choi/proposal-hack-pipes#1]
> The head and the body of a pipeline cannot be comma-separated lists. That is, (value0, value1) |> foo(?, 0) is an early syntax error. This design is to prevent confusion about which value is bound to the topic reference.

Let’s say i have a conceptual async pipeline with a side effect in the middle:
```jsx
a().then(b).then(() => sideEffect()).then(d).then(e);
```
This ensures the correct ordering, and ensures sideEffect does not accidentally get the output of `b`.

Now let’s say i want to represent a similar synchronous workflow as an actual pipeline:
```jsx
a() |> b(?) |> sideEffect() |> d() |> e(?)
```

The requirement to use the `?`, and the inability to use the comma operator even inside parens, means that there’s no way to represent that either sideEffect or d take no arguments.

How would i accomplish this?

**Comment by js-choi** [comment]
This is a good question. 

If we expressed that synchronous example with variables, it’d be equivalent to:
```js
const v0 = a();
const v1 = b(v0);
const v2 = sideEffect();
const v3 = d();
const v4 = e(v3);
```
In this case, I would argue that it’s a good thing that the current rules force a separation into separate pipelines, because this makes the data flow is visually clearer:
```js
a() |> b(?); sideEffect(); d() |> e(?);
```
Because, really, the example above involves *three* data flows: one from `a` to `b`, one involving only `sideEffect`, and one from `d` to `e`. The fact that the data flows occur sequentially doesn’t necessarily mean they should be merged into a single pipeline. A single pipeline visually implies a continuous flow of data from start to end.

In contrast, using `.then` outside of an `async` function forces a single unbroken `.then` chain—*not* because it’s actually a single continuous flow of data but rather as a mere artifact of the sequential async control flow. But there are still three separate flows of data inside the `.then` chain, even if they are not immediately visually apparent. In this async case, too, multiple pipelines make the data flows clearer:
```js
await a() |> await b(?); await sideEffect(); await d() |> await e(?);
```

However, it is true that there might be a trade-off here, and details like these are certainly not set in stone.

**Comment by ljharb** [comment]
I agree that breaking up the chain/pipeline achieves what I'm asking :-)

It seems a bit overly opinionated to me to force users to pass an argument every time in order to use the pipeline operator.

**Comment by js-choi** [comment]
It is certainly true that this may be an overly opinionated safety rail, and that rail could certainly be removed. I don’t have a strong philosophical opinion about that aspect—except that it seemed like a good idea, it probably wouldn’t get in the way of everyday coding, and it may catch some real accidental bugs at compile time.

The other issue is that removing this restriction would break forward compatibility with a smart-mix—that is, it would make it impossible to add a tacit mode (without placeholders) to this same operator. This might not actually matter, though. 

I’ll remove the restriction later today. It could always be added back later if this proposal advances far enough to start to bikeshed.

**Comment by ljharb** [comment]
Which restriction - "must be a placeholder", or "no comma operator"?

I do think it's fine if i have to do either `b |> ?, sideEffect() |> c` or `b |> (?, sideEffect()) |> c` for this use case.

**Comment by js-choi** [comment]
I’ll remove the comma-expression restriction while keeping the placeholder-required restriction.

**Comment by js-choi** [comment]
We all do need to interpose `console.log(something)` in the middle of things, sometimes.
