### ISSUE TITLE
"Right associative" seems confusing to me

### ISSUE THREAD

**Issue by getify** [js-choi/proposal-hack-pipes#14]
I apologize in advance what I'm sure I'm missing but can't quite understand. But I am really confused by the assertions that `|>` is right associative, and trying to untangle it.

Let's assume this expression for discussion:

```js
fnOne() |> fnTwo(#) |> fnThree(#)
```

If that expression is "right-associative", then I expect that means it would be treated as:

```js
fnOne() |> (  fnTwo(#) |> fnThree(#)  )
```

No?

At least, that's my understanding of the notion of "right associative" (in terms of operators), in that when an expression has multiple operators of the same precedence, and no other `( .. )` grouping present to override, the implicit grouping is then done right-to-left.

Except, that right-to-left grouping as shown doesn't make any sense to me... how could it evaluate an expression like `fnTwo(#) |> fnThree(#)` in isolation first, without the left-hand `#` context having already been bound (by evaluating/running the left-hand)?

I guess what I'm saying is, it seems to me like it always has to go left-to-right in its implicit grouping, because that's where you get the left-hand `#` context from. So, it seems to me like that expression has to run as if it were written like this:

```js
(  fnOne() |> fnTwo(#)  ) |> fnThree(#)
```

Right?

And if it has to execute in that order, isn't it more accurate to assert that it's "left associative" (implicitly groups from the left)?

Again, apologies for what I'm sure I'm missing (and hoping what I overlooked is not super obvious).

**Comment by tabatkins** [comment]
Correct, it should be left-associative; nothing else makes sense. I assume it was just a slip of the fingers.

**Comment by js-choi** [comment]
Well, `|>` is functionally *bidirectionally* associative.

```js
(fnOne() |> fnTwo(#)) |> fnThree(#)
fnOne() |> (fnTwo(#) |> fnThree(#))
```

These currently are equivalent.

In the latter case:

1. `fnOne()` is still evaluated first.
2. Then its result is bound to the topic over the outer pipe’s body `(fnTwo(#) |> fnThree(#))`.
3. That pipe body is another, inner pipe expression, and its head `fnTwo(#)` is evaluated first, and in that context `#` is currently the result of `fnOne()`. 
4. And that result from `fnTwo` in turn is bound to topic over the inner pipe’s body, `fnThree(#)`.
5. Then the inner pipe’s body is evaluated, and that result because the inner pipe expression’s result, which then becomes the outer pipe body’s result, which then becomes the outer pipe expression’s result.

It’s like nested closures:
```js
do { const t0 = fnOne(); do { const t1 = fnTwo(t0); fnThree(t1) }; }
```

It’s also how in many languages `let b = a + 1 in let c = b + 1 in c + 1` is right associative: `let b = a + 1 in (let c = b + 1 in (c + 1))`; the result is whatever `c + 1` is with the `b` and `c` bindings, but `a + 1` still evaluates first, followed by `b + 1`.

The reason why I had made it right associative was in case we went with something like [pipe adverbs](https://gist.github.com/js-choi/661874875fc7b119db13d3b50f06b12b), which would *require* right associativity by allowing named pipe variables, short-circuiting, and other modified pipes. 

However, I have abandoned exploring pipe adverbs or other extensions to pipes, in favor of exploring [F# computation expressions](https://gist.github.com/js-choi/854ccbc34787c697ea1f8458d6a1d660). So I no longer have strong opinions on which way the associativity should go, because they are functionally equivalent.

I’m fine with switching the associativity back to left, as long as we’re fine with foreclosing any possibility of named pipe variables or short-circuiting pipes. We’d have to switch it back in the Babel plugin too, which uses right associativity right now. CC: @nicolo-ribaudo.

**Comment by getify** [comment]
Just to be clear... are we asserting that the parser currently treats the code as right-associative, and thus produces a right-associative nesting in the AST, but then the JS engine special cases such a grouped structure and evaluates it top-down rather than bottom-up?

If that's the case, do we have other places *in JS* where we parse as right-associative but execute as left-associative? I've personally never heard of "bidirectional associativity" before, so that's I guess where my confusion is coming from. I thought it had to be one or the other.

**Comment by js-choi** [comment]
Sorry, by “bidirectional associativity”, I mean that the left grouping and right grouping are functionally equivalent. That is:
```js
fnOne() |> fnTwo(#) |> fnThree(#)
```
…and:
```js
fnOne() |> (fnTwo(#) |> fnThree(#))
```
…and:
```js
fnOne() |> (fnTwo(#) |> fnThree(#))
```
…will always evaluate to the same thing.

This is regardless of which way the parser decides to group the first expression. We can define it either way.

**Comment by getify** [comment]
But... "will always evaluate to the same thing." and "will parse the same" are not at all the same assertion, right? So I think it remains that the parser currently produces a tree that looks right-associative, but then the engine special cases that kind of node and evaluates it as if it had been left-associative. Or...?

**Comment by js-choi** [comment]
Sorry, I might be misunderstanding something. I’m not sure what you mean by engine special casing during evaluation. Whether or not the parser groups leftward or rightward, the engine needs to do no special casing during evaluation; the evaluation rules are the same either way.

**Comment by nicolo-ribaudo** [comment]
`**` is parsed as right-associative but it's evaluated left-to-right. You can verify it with
```js
const it = x => (console.log(x), x);
it(2) ** it(1) ** it(3)
```

It logs `2, 1, 3`, but it returns `2` (which is `2**(1**3)` and not `(2**1)**3`). In general, associativity has nothing to do with execution order and everything in JS is executed left-to-right.

> I’m fine with switching the associativity back to left, as long as we’re fine with foreclosing any possibility of named pipe variables or short-circuiting pipes.

Since for now the associativity isn't observable, I don't see any reason to do it. We can document it as just "associative" (without saying left/right), similarly to how `+` and `*` are described in math.

**Comment by getify** [comment]
I don't think what I'm referring to is "execution order" as much as I'm referring to "tree traversal" order... IIUC, typically you'd do in-order traversal, but I think with these node types that doesn't work, and you have to traverse differently. Is that not true?

**Comment by nicolo-ribaudo** [comment]
If you imagine a transpiler that transforms `x |> f(#)` into `_tmpX = x, f(_tmpX)` (going top-to-bottom, or in-order, in the parser tree), you can see that the associativity changes the transpiler result but not the evaluation/execution order:

1. Right-associative
   ```js
   fnOne() |> (fnTwo(#) |> fnThree(#))
   // ->
   _tmp1 = fnOne(), (fnTwo(_tmp1) |> fnThree(#))
   // ->
   _tmp1 = fnOne(), (_tmp2 = fnTwo(_tmp1), fnThree(_tmp2))
   ```
2. Left-associative
   ```js
   (fnOne() |> fnTwo(#)) |> fnThree(#)
   // ->
   _tmp1 = (fnOne() |> fnTwo(#)), fnThree(_tmp1)
   // ->
   _tmp1 = (_tmp2 = fnOne(), fnTwo(_tmp2)), fnThree(_tmp1)
   ```

**Comment by js-choi** [comment]
@nicolo-ribaudo is correct. With `do` expressions or IIFEs…

```js
// Right-associative pipes
fnOne() |> (fnTwo(#) |> fnThree(#))

// Right-associative dos
do {
  const t0 = fnOne();
  do {
    const t1 = fnTwo(t0);
    fnThree(t1);
  };
}

// Right-associative IIFEs
(t0 =>
  (t1 =>
    fnThree(t1)
  )(fnTwo(t0))
)(fnOne)

// Left-associative pipes
(fnOne() |> fnTwo(#)) |> fnThree(#)

// Left-associative dos
do {
  const t1 = do {
    const t0 = fnOne();
    fnTwo(t0);
  };
  fnThree(t1);
}

// Left-associative IIFEs
(t1 =>
  fnThree(t1)
)(
  (t0 =>
    fnTwo(t0)
  )(fnOne())
)
```

All six of these expressions are functionally equivalent, without any special evaluation rules. The difference is not observable to the developer. Any change to `|>`’s associativity would only be a spec-editorial change.

**Comment by getify** [comment]
I agree here that currently, from what you describe, the associativity of this "operator" is not **observable** in the outcome sense. Thank you for those clarifications. I could already have deduced that before posting the thread, but it's helpful to be clear, even for posterity.

However... speaking as someone who teaches JS for a living, the perspective I have is a label like "left associative" or "right associative" typically doesn't matter to a JS developer, except in certain cases, where the mental model they construct *does* matter. For example, when parsing a nested ternary, and trying to mentally decide what its outcome will be, you need to actually understand that the ternary is, unlike most other operators you deal with, right-associative, so you need to know where to mentally draw the parentheses in your head, so that you properly group the ternary expressions/sub-expressions. That's a case where the associativity not only matters to the parser/engine, but also to the developer.

Take then the `**` operator brought up earlier... this one being right-associative also matters not only to the parser/engine but to the developer, because in `3 ** 5 ** 7`, if you're trying to mentally model what happens, you will get a very different result from `(3 ** 5) ** 7` than you will from `3 ** (5 ** 7)`, right? So again, having the developer know the associativity is helpful, and... as you assert, that fact is **observable**.

It's in this mental model sense, that I think it still matters for `|>`, as one grouping is reasonable and the other is non-sensical (hence my whole reason for posting this thread).

I imagine others reading "Pipe is right-associative" in the spec, or on MDN, or on some unsuspecting blog post that just copy-pasted from one of those, and perhaps then trying to do what I did and translate that into a grouped expression, then scratching their head and thinking, "hmmm.... that's weird, how that can be?" just like I did.

The label you use for it matters, in the learnability and mental-model sense, even if the executed outcome doesn't change.

If you use the label "right associative", I think it will lead to confusion for some (maybe not many) like it did for me. If you use "left associative", it would lead to far less chance of confusion for those few.

But (as you said) that may limit further possible enhancements to the feature later -- although even that's suspect to me, since the outcome isn't observable, and the change would only be internally in parsers.

If you use "associative", I wouldn't have any idea what that means, and I wouldn't know how to figure out the answer, since that's a deliberately less-specific, more-vague term, thus googling it would be much harder.

If you use "bi-directionally associative", I also wouldn't understand it (before this thread), but I would at least know I needed to look that up. Hopefully a google search would lead me to a thread like this, or (even better) an MDN page or an internal definition in the spec for this detail.

----

I'd argue it also matters for tool authors (such as Babel's plugin, yes, but any number of other tools that might operate on the code)... they may for example be in the habit of performing associativity grouping transforms (e.g., hoisting out a sub-expression, as your example did), and they may not be aware, when the spec said "right associative", that it wasn't strictly "right associative" the way others might be.

I definitely had a tool like this years back (not currently maintained), and I think it probably would have broken on this new construct. If I read "right associative" and implemented my transforms the way I might have assumed I could, I think it might produce incorrect code. I would need to further/deeper understand that it's not really "right associative" in the strictest sense, but more this "left-right associative", or "bi-directionally associative", or whatever.

**Comment by js-choi** [comment]
@getify: I think you have good points. I’d be happy to remove the note about associativity completely, if that’d help the learnability. Do you think that’d solve this issue? After all, people can form their own mental models about the grouping without effects on the actual result.

**Comment by getify** [comment]
>  I’d be happy to remove the note about associativity completely

Among the various options, I'm less opposed to that, than others.

In fairness, it's less like an operator than `+` anyway, it's a little more like `...`, so maybe staying away from "associativity" and other terms typically more closely related to actual operators is useful.

> Do you think that’d solve this issue?

Probably, yes. But depends.

Will the final TC39 spec have to, for any reason, spell out the associativity? If so, we might still end up in this problem eventually.

Will a future contemplated enhanced version of this feature need to come back and say "hey, that operator is now specifically right-associative, even though we never said anything about that before now"? Again, that sort of future change could re-introduce the problem.

**Comment by js-choi** [comment]
@getify: I’ll remove any mention of associativity from the explainer, so that users can make their own mental models of how it works, and it’d be equivalent.

Your points about extending pipe in the future are well taken. I do think the final spec syntax can group either way, left or right. Barring any extensions to pipe, changing the associativity would be merely an editorial change, since the difference is not observable.

If we elect to extend pipes in the future in some way that requires right associativity, then we could cross that bridge; it wouldn’t break backwards compatibility with JS code, although, as you mention, a build tool might couple itself tightly to pipe’s associativity (hopefully not). At least for Babel, @nicolo-ribaudo thinks that there would be little problem with switching between associativities with major versions. I’m happy to hear differing opinions, though.

I’ll work on removing the associativity mention in a bit.
